### ISSUE TITLE
comparison with https://github.com/euank/pazi/

### ISSUE THREAD

**Issue by cgwalters** [jlebon/codeswitch#1]
Did you see https://github.com/euank/pazi/ ?

**Comment by jlebon** [comment]
Ahhh, nice. No, I hadn't really looked at what's out there, this project being more of an excuse to practice some Rust. :)

It looks more complex though I do like that it's more generic beyond just git repos and requires no upfront scanning. Will have to give it a spin.

**Comment by jlebon** [comment]
This is many years later but I recently tried out https://github.com/ajeetdsouza/zoxide which is similar to pazi and I've come to the conclusion that at least for developers, something tailored to codebases provides a better experience. How zoxide does substring matching is just weird (e.g. typing `os` should jump to my checkout of openshift/os, not ostreedev/ostree, even if it has a higher frecency score). In codeswitch, if you want to be able to type shorter names, the recommendation is to make symlinks (e.g. I have an `ost` symlink to my `ostreedev/ostree` checkout so I can just type `code ost`, but also it makes my prompt shorter too).

I can see wanting to use an autojumper for everything else but I'd say 90% of my need for "autojumping" to a completely different directory structure is to jump between different codebases. I think another reason too is that I heavily use tmux, and in that flow, it's much simpler and nicer to just open a different pane in a different directory than to switch back and forth between multiple directories. And finally, there is also [fzf's Ctrl-T](https://github.com/junegunn/fzf?tab=readme-ov-file#key-bindings-for-command-line) which is helpful when navigating within the same directory structure.

I don't like also [the ambiguity](https://github.com/ajeetdsouza/zoxide/issues/765) of jumping to a random directory and then having to verify that it landed in the right one. codeswitch will make you provide more substrings if it's ambiguous to narrow it down.
